python train.py \
    --net_type resnet \
    --dataset imagenet \
    --batch_size 256 \
    --lr 0.1 \
    --depth 50 \
    --epochs 300 \
    --expname ResNet50 \
    -j 40 \
    --beta 1.0 \
    --cutmix_prob 1.0 \
    --no-verbose
